package b00394105_comp09044_cw2_final;

import javax.swing.JOptionPane;

public class RegisterUI extends javax.swing.JFrame {
    // Singleton is passed for the UserList to ensure sync
    UserList userList = UserListSingleton.getInstance().getUserList();

    /**
     * Creates new form RegisterUI
     */
    public RegisterUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        newUsernameFld = new javax.swing.JTextField();
        newPasswordFld = new javax.swing.JTextField();
        adminCB = new javax.swing.JComboBox<>();
        newUsernameLbl = new javax.swing.JLabel();
        newPasswordLbl = new javax.swing.JLabel();
        newAdminLbl = new javax.swing.JLabel();
        newAccountBtn = new javax.swing.JButton();
        quitBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        titleLbl.setText("Register New Account");

        newUsernameFld.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        newPasswordFld.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        adminCB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        adminCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "true", "false" }));

        newUsernameLbl.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        newUsernameLbl.setText("New Username: ");

        newPasswordLbl.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        newPasswordLbl.setText("New Password: ");

        newAdminLbl.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        newAdminLbl.setText("Admin?: ");

        newAccountBtn.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        newAccountBtn.setText("Create Account");
        newAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAccountBtnActionPerformed(evt);
            }
        });

        quitBtn.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        quitBtn.setText("Quit");
        quitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBtnActionPerformed(evt);
            }
        });

        cancelBtn.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cancelBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titleLbl)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(newUsernameLbl)
                                                .addComponent(newPasswordLbl))
                                            .addComponent(newAdminLbl))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(newPasswordFld, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(newUsernameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(adminCB, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(newAccountBtn)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newUsernameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newUsernameLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPasswordFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPasswordLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newAdminLbl))
                .addGap(30, 30, 30)
                .addComponent(newAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBtnActionPerformed
        // Will quit program when pressed
        System.exit(0);
    }//GEN-LAST:event_quitBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // When pressed, will make the LogInUI GUI visible and RegisterUI invisible
        LogInUI logInUI = new LogInUI();
        logInUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void newAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAccountBtnActionPerformed
        // the new users username and password will be taken from the text fields
        // the users admin status will be taken from the combo-box then turned into a boolean to be passed properly
        // the users userID and listID (essentially the same at this point) will be made from the current number of users
        // (first user will be 0, since there is no users. Then the next will be 1 and so forth)
        String newUsername = newUsernameFld.getText();
        String newPassword = newPasswordFld.getText();
        String getAdmin = adminCB.getSelectedItem().toString();
        Boolean newAdmin = Boolean.parseBoolean(getAdmin);
        Integer newUserID = userList.checkCount();
        Integer newListID = userList.checkCount();
        
        // Check is made if the username in the text field already exists
        userList.checkUser(newUsername);
        if(userList.checkUser(newUsername) == true){
            // If they do exist then a message is displayed and nothing else happens
            JOptionPane.showMessageDialog(this, "Username is already taken...");
        } else {
            // Otherwise the information for the new user will be passed to the UserList addUser method
            userList.addUser(newUsername, newPassword, newUserID, newListID, newAdmin);
            if(newAdmin == true){
                // If the user selected to be an admin then a unique message will be displayed
                // User will then be returned to the LogInUI
                JOptionPane.showMessageDialog(this, "New Admin added...");
                LogInUI logInUI = new LogInUI();
                logInUI.setVisible(true);
                this.setVisible(false);
            } else if (newAdmin == false) {
                // If the user did not select to be an admin then a unique message will be displayed
                // User will then be returned to the LogInUI
                JOptionPane.showMessageDialog(this, "New User added...");
                LogInUI logInUI = new LogInUI();
                logInUI.setVisible(true);
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_newAccountBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> adminCB;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton newAccountBtn;
    private javax.swing.JLabel newAdminLbl;
    private javax.swing.JTextField newPasswordFld;
    private javax.swing.JLabel newPasswordLbl;
    private javax.swing.JTextField newUsernameFld;
    private javax.swing.JLabel newUsernameLbl;
    private javax.swing.JButton quitBtn;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
